version: '3.10'

networks:
  dev_network:

services:
  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      dev_network:
        aliases:
          - db-redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
#    entrypoint: celery -A flask_celery.celery_app.celery_app worker -c 2
#    entrypoint: bash run_celery.sh
    container_name: celery
    depends_on:
      - redis
    networks:
      dev_network:
    volumes:
      - ./flask_celery/${ML_PACKAGE}/${ML_STORAGE}:/app/flask_celery/${ML_PACKAGE}/${ML_STORAGE}

  app:
    build:
      context: .
    environment:
      CELERY_BROKER: ${CELERY_BROKER}
      CELERY_BACKEND: ${CELERY_BACKEND}
    ports:
      - "5000:5000"
    container_name: flask_app
    depends_on:
      - celery
    networks:
      dev_network:
        aliases:
          - flask
    volumes:
      - ./flask_celery:/app/flask_celery
