version: '3.10'

networks:
  dev_network:

services:
  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      dev_network:
        aliases:
          - db-redis

  celery:
    build:
      context: .
    environment:
      BACKEND: ${CELERY_BACKEND}
      BROKER: ${CELERY_BROKER}
    entrypoint: celery -A tasks.celery_app worker
    depends_on:
      - redis
    networks:
      dev_network:
    volumes:
      - ./app:/app





