version: '3.10'

networks:
  dev_network:

services:
  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      dev_network:
        aliases:
          - db-redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      CELERY_BROKER: "redis://db-redis:6379/1"
      CELERY_BACKEND: "redis://db-redis:6379/2"
#      CELERY_BROKER: ${CELERY_BROKER}
#      CELERY_BACKEND: ${CELERY_BACKEND}
#    entrypoint: celery -A celery_app.celery_app1 worker -c 1
#    entrypoint: bash run_celery.sh
    container_name: celery
    depends_on:
      - redis
    networks:
      dev_network:
    volumes:
      - ./app:/app

